netty:
  server:
    port: 18000
    decode:
      request: false
    encode:
      response: false
  client:
    server:
      address: localhost
      port: 18000
    decode:
      response: false
    encode:
      request: false
